# Generated by Django 6.0.6 on 2026-08-03 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='AIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('summary', 'Summary'), ('explain', 'Explain'), ('notes', 'Study Notes'), ('quiz', 'Quiz'), ('chat', 'Chat')], max_length=20)),
                ('prompt_hash', models.CharField(max_length=64)),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_responses', to='encyclopedia.entry')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('article', 'feature', 'prompt_hash')},
            },
        ),
    ]
